#! perl

# $Id: harness 26420 2008-03-16 15:11:52Z bernhard $

# pragmata
use strict;
use warnings;
use 5.008;
use lib qw( . lib ../lib ../../lib ../../lib );

# language is the directory where the language implementation lives
# See perldoc Parrot::Test::Harness for details

use Parrot::Test::Harness language => 'PIR';
